
# Use postgres/example user/password credentials
        version: '3.5'

        services:
          postgres:
            container_name: postgres_nlw
            image: postgres
            restart: always
            environment:
              POSTGRES_USER: admin
              POSTGRES_PASSWORD: admin
              POSTGRES_DB: pg_nlw
            ports:
              - "5434:5432"